version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: freelancer-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: freelancer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: freelancer-api
    depends_on:
      - postgres
    ports:
      - "5164:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=freelancer_db;Username=postgres;Password=postgres"
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: freelancer-ui
    depends_on:
      - backend
    ports:
      - "4200:80"
    restart: unless-stopped

volumes:
  postgres_data: 